/// This file is automatically generated by EventReferencer script. Made by sir.woody


/// Method <see cref="UnityEngine.Object.set_name"/>
/// Referenced by game object named GameObject (1) (fileID: 1472306635, guid: 9fc0d4010bbf28b4594072e72b8655ab)
/// By component Button.cs (path: Packages/com.unity.ugui/Runtime/UI/Core/Button.cs, component fileID: 1472306636)
/// In file Assets\Scenes\SampleScene.unity (guid: 9fc0d4010bbf28b4594072e72b8655ab).


/// Method <see cref="Puzzle.ResetPuzzle"/>
/// Referenced by game object named GameObject (1) (fileID: 1472306635, guid: 9fc0d4010bbf28b4594072e72b8655ab)
/// By component Button.cs (path: Packages/com.unity.ugui/Runtime/UI/Core/Button.cs, component fileID: 1472306636)
/// In file Assets\Scenes\SampleScene.unity (guid: Assets\Scenes\SampleScene.unity).


/// Method <see cref="UnityEngine.MonoBehaviour.CancelInvoke"/>
/// Referenced by game object named GameObject (1) (fileID: 1472306635, guid: 9fc0d4010bbf28b4594072e72b8655ab)
/// By component Button.cs (path: Packages/com.unity.ugui/Runtime/UI/Core/Button.cs, component fileID: 1472306636)
/// In file Assets\Scenes\SampleScene.unity (guid: Assets\Scenes\SampleScene.unity).


/// Method <see cref="UnityEngine.Object.set_name"/>
/// Referenced by game object named GameObject (fileID: 1536446041, guid: 9fc0d4010bbf28b4594072e72b8655ab)
/// By component Button.cs (path: Packages/com.unity.ugui/Runtime/UI/Core/Button.cs, component fileID: 1536446042)
/// In file Assets\Scenes\SampleScene.unity (guid: 9fc0d4010bbf28b4594072e72b8655ab).


/// Method <see cref="Puzzle.ResetPuzzle"/>
/// Referenced by game object named GameObject (fileID: 1536446041, guid: 9fc0d4010bbf28b4594072e72b8655ab)
/// By component Button.cs (path: Packages/com.unity.ugui/Runtime/UI/Core/Button.cs, component fileID: 1536446042)
/// In file Assets\Scenes\SampleScene.unity (guid: Assets\Scenes\SampleScene.unity).


/// Method <see cref="UnityEngine.MonoBehaviour.CancelInvoke"/>
/// Referenced by game object named GameObject (fileID: 1536446041, guid: 9fc0d4010bbf28b4594072e72b8655ab)
/// By component Button.cs (path: Packages/com.unity.ugui/Runtime/UI/Core/Button.cs, component fileID: 1536446042)
/// In file Assets\Scenes\SampleScene.unity (guid: Assets\Scenes\SampleScene.unity).


